name: Pickture
options:
  bundleIdPrefix: com.jaeppetto.pickture
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule

packages:
  FirebaseAnalytics:
    url: https://github.com/firebase/firebase-ios-sdk
    version: "11.0.0"

configs:
  Debug: debug
  Release: release

schemes:
  Pickture:
    build:
      targets:
        Pickture: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PicktureTests
        - PicktureUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Pickture:
    type: application
    platform: iOS
    sources:
      - path: Pickture
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Pickture/Resources/Assets.xcassets
      - path: Pickture/Resources/Localizable
      - path: Pickture/Resources/Info.plist
      - path: Pickture/Resources/Fonts
      - path: Pickture/Resources/GoogleService-Info.plist
        optional: true
    dependencies:
      - package: FirebaseAnalytics
        product: FirebaseAnalytics
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaeppetto.pickture
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Pickture/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        CODE_SIGN_STYLE: Automatic
    info:
      path: Pickture/Resources/Info.plist
      properties:
        NSPhotoLibraryUsageDescription: "사진 라이브러리를 분석하고 정리하기 위해 접근 권한이 필요합니다."
        UIAppFonts:
          - PressStart2P-Regular.ttf
        UILaunchScreen:
          UIColorName: Background

  PicktureTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PicktureTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pickture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaeppetto.pickture.tests
        GENERATE_INFOPLIST_FILE: true

  PicktureUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PicktureUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pickture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaeppetto.pickture.uitests
        GENERATE_INFOPLIST_FILE: true
