name: Pickture
options:
  bundleIdPrefix: com.pickture
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule

configs:
  Debug: debug
  Release: release

targets:
  Pickture:
    type: application
    platform: iOS
    sources:
      - path: Pickture
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Pickture/Resources/Assets.xcassets
      - path: Pickture/Resources/Localizable
      - path: Pickture/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pickture.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Pickture/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        CODE_SIGN_STYLE: Automatic
    info:
      path: Pickture/Resources/Info.plist

  PicktureTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PicktureTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pickture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pickture.app.tests
        GENERATE_INFOPLIST_FILE: true

  PicktureUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PicktureUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pickture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pickture.app.uitests
        GENERATE_INFOPLIST_FILE: true
